coverage:
  paths:
    - coverage/lcov.info
  acceptable: 100%
  badge:
    path: docs/assets/coverage.svg
codeToTestRatio:
  code:
    - "src/**/*.ts"
    - "!src/main.ts"
    - "!src/types.ts"
  test:
    - "__tests__/**/*.test.ts"
  badge:
    path: docs/assets/code-to-test-ratio.svg
push:
  if: is_default_branch
  message: "chore: update metric badges [skip ci]"
