coverage:
  paths:
    - coverage/lcov.info
  acceptable: 90%
codeToTestRatio:
  code:
    - "src/**/*.ts"
    - "!src/main.ts"
  test:
    - "__tests__/**/*.test.ts"
testExecutionTime:
  if: true
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
comment:
  if: is_pull_request
  deletePrevious: true
report:
  if: is_default_branch
  datastores:
    - artifact://${GITHUB_REPOSITORY}
summary:
  if: true
