import { computeTopReviewerSummary } from "../analyze/top-reviewers";
import { MAX_REVIEWS_PER_PR } from "../collect/graphql-queries";
import type { AnalysisResult } from "../types";
import { formatDuration } from "../utils/format";
import { logger } from "../utils/logger";
import { isRateLimitError, retry } from "../utils/rate-limit";
import { escapeHtml } from "../utils/sanitize";

const COMMENT_MARKER = "<!-- review-insights-report -->";

/**
 * Builds the markdown body for the PR comment.
 */
function buildCommentBody(analysis: AnalysisResult): string {
  const { userStats, bias, pullRequests, dateRange, includeBots } = analysis;

  const filteredPRs = includeBots
    ? pullRequests
    : pullRequests.filter((pr) => !pr.authorIsBot);
  const totalPRs = filteredPRs.length;
  const topReviewerSummary = computeTopReviewerSummary(userStats);
  const biasDetected = bias.flaggedPairs.length > 0;

  const truncatedPRs = filteredPRs.filter(
    (pr) => pr.reviews.length >= MAX_REVIEWS_PER_PR,
  );

  const truncationWarning =
    truncatedPRs.length > 0
      ? `> **Warning:** ${truncatedPRs.length} PR(s) have ${MAX_REVIEWS_PER_PR}+ reviews and may have truncated data (${truncatedPRs
          .slice(0, 10)
          .map((pr) => `#${pr.number}`)
          .join(
            ", ",
          )}${truncatedPRs.length > 10 ? ", ..." : ""}). Statistics for these PRs may be incomplete.\n\n`
      : "";

  const statsRows = userStats
    .slice(0, 15)
    .map(
      (u) =>
        `| ${escapeHtml(u.login)} | ${u.reviewsGiven} | ${u.reviewsReceived} | ${u.approvals} | ${u.changeRequests} | ${u.avgTimeToFirstReviewMs != null ? formatDuration(u.avgTimeToFirstReviewMs) : "N/A"} | ${u.medianTimeToFirstReviewMs != null ? formatDuration(u.medianTimeToFirstReviewMs) : "N/A"} |`,
    )
    .join("\n");

  const biasSection = biasDetected
    ? `### Bias Warnings\n\n| Reviewer | Author | Count | Z-Score |\n|----------|--------|-------|---------|\n${bias.flaggedPairs
        .sort((a, b) => b.zScore - a.zScore)
        .map(
          (fp) =>
            `| ${escapeHtml(fp.reviewer)} | ${escapeHtml(fp.author)} | ${fp.count} | ${fp.zScore.toFixed(2)} |`,
        )
        .join("\n")}\n`
    : "";

  return `${COMMENT_MARKER}
## Review Insights Report

${truncationWarning}**Date range:** ${escapeHtml(dateRange.since)} to ${escapeHtml(dateRange.until)}

| Metric | Value |
|--------|-------|
| Total PRs analyzed | ${totalPRs} |
| Unique reviewers | ${topReviewerSummary.reviewerCount} |
| Top reviewers | ${topReviewerSummary.topReviewers.length > 0 ? `${escapeHtml(topReviewerSummary.topReviewers.join(", "))} (${topReviewerSummary.maxReviewsGiven} reviews each)` : "N/A"} |
| Max reviews given | ${topReviewerSummary.maxReviewsGiven ?? "N/A"} |
| Bias detected | ${biasDetected ? `Yes (${bias.flaggedPairs.length} pairs)` : "No"} |
| Gini coefficient | ${bias.giniCoefficient.toFixed(2)} |

### Reviewer Stats

| User | Given <sup title="Unique PRs reviewed">?</sup> | Received <sup title="Total review submissions received, including multiple reviews on the same PR">?</sup> | Approvals | Change Requests | Avg 1st Review | Median 1st Review |
|------|-------|----------|-----------|-----------------|----------------|-------------------|
${statsRows}

${biasSection}
---
<sub>Generated by review-insights</sub>
`;
}

/**
 * Creates or updates a PR comment containing the review insights report.
 * Uses a hidden HTML marker to identify existing comments for updates.
 *
 * Requires `pull-requests: write` permission in the workflow.
 * @see {@link https://docs.github.com/en/rest/issues/comments#list-issue-comments} listComments
 * @see {@link https://docs.github.com/en/rest/issues/comments#create-an-issue-comment} createComment
 * @see {@link https://docs.github.com/en/rest/issues/comments#update-an-issue-comment} updateComment
 */
export async function postPRComment(
  octokit: ReturnType<typeof import("@actions/github").getOctokit>,
  owner: string,
  repo: string,
  prNumber: number,
  analysis: AnalysisResult,
): Promise<void> {
  const body = buildCommentBody(analysis);

  try {
    // List all comments using pagination to find one with our marker
    const comments = await retry(() =>
      octokit.paginate(octokit.rest.issues.listComments, {
        owner,
        repo,
        issue_number: prNumber,
        per_page: 100,
      }),
    );

    const existingComment = comments.find((c) =>
      c.body?.includes(COMMENT_MARKER),
    );

    if (existingComment) {
      logger.info(
        `Updating existing review-insights comment #${existingComment.id}`,
      );
      await retry(() =>
        octokit.rest.issues.updateComment({
          owner,
          repo,
          comment_id: existingComment.id,
          body,
        }),
      );
    } else {
      logger.info("Creating new review-insights comment");
      await retry(() =>
        octokit.rest.issues.createComment({
          owner,
          repo,
          issue_number: prNumber,
          body,
        }),
      );
    }
  } catch (err: unknown) {
    if (isPermissionError(err)) {
      throw new Error(
        'Insufficient permissions to post PR comments. Add "pull-requests: write" to your workflow permissions.',
      );
    }
    throw err;
  }
}

function isPermissionError(error: unknown): boolean {
  if (error === null || typeof error !== "object") {
    return false;
  }

  const record = error as Record<string, unknown>;
  if (record.status !== 403) {
    return false;
  }

  return !isRateLimitError(error);
}
